//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\IMP.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace IMP {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IMPParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IIMPListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IMPParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] IMPParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IMPParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] IMPParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IMPParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] IMPParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IMPParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] IMPParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Statment</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatment([NotNull] IMPParser.StatmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Statment</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatment([NotNull] IMPParser.StatmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] IMPParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] IMPParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfThenElse</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfThenElse([NotNull] IMPParser.IfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfThenElse</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfThenElse([NotNull] IMPParser.IfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyStatment</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatment([NotNull] IMPParser.EmptyStatmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyStatment</c>
	/// labeled alternative in <see cref="IMPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatment([NotNull] IMPParser.EmptyStatmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableDeclaration</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] IMPParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableDeclaration</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] IMPParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableAssignment</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAssignment([NotNull] IMPParser.VariableAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableAssignment</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAssignment([NotNull] IMPParser.VariableAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Print</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] IMPParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Print</c>
	/// labeled alternative in <see cref="IMPParser.statementSemicolonRequired"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] IMPParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Variables</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariables([NotNull] IMPParser.VariablesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Variables</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariables([NotNull] IMPParser.VariablesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] IMPParser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] IMPParser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] IMPParser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] IMPParser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Disjunction</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjunction([NotNull] IMPParser.DisjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Disjunction</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjunction([NotNull] IMPParser.DisjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Lesser</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLesser([NotNull] IMPParser.LesserContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Lesser</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLesser([NotNull] IMPParser.LesserContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Negation</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] IMPParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Negation</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] IMPParser.NegationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Brackets</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrackets([NotNull] IMPParser.BracketsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Brackets</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrackets([NotNull] IMPParser.BracketsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Bool</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] IMPParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Bool</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] IMPParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Conjunction</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] IMPParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Conjunction</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] IMPParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] IMPParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] IMPParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] IMPParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="IMPParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] IMPParser.IntContext context);
}
} // namespace IMP
