//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\BasicMath.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BasicMath {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BasicMathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IBasicMathVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>BRACKETS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBRACKETS([NotNull] BasicMathParser.BRACKETSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MULTIPLY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMULTIPLY([NotNull] BasicMathParser.MULTIPLYContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UNARY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUNARY([NotNull] BasicMathParser.UNARYContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATOM</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATOM([NotNull] BasicMathParser.ATOMContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PLUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPLUS([NotNull] BasicMathParser.PLUSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MINUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMINUS([NotNull] BasicMathParser.MINUSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DIVIDE</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDIVIDE([NotNull] BasicMathParser.DIVIDEContext context);
}
} // namespace BasicMath
