//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\BasicMath.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BasicMath {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBasicMathListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class BasicMathBaseListener : IBasicMathListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>BRACKETS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBRACKETS([NotNull] BasicMathParser.BRACKETSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BRACKETS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBRACKETS([NotNull] BasicMathParser.BRACKETSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MULTIPLY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMULTIPLY([NotNull] BasicMathParser.MULTIPLYContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MULTIPLY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMULTIPLY([NotNull] BasicMathParser.MULTIPLYContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UNARY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUNARY([NotNull] BasicMathParser.UNARYContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UNARY</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUNARY([NotNull] BasicMathParser.UNARYContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ATOM</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterATOM([NotNull] BasicMathParser.ATOMContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ATOM</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitATOM([NotNull] BasicMathParser.ATOMContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PLUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPLUS([NotNull] BasicMathParser.PLUSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PLUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPLUS([NotNull] BasicMathParser.PLUSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MINUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMINUS([NotNull] BasicMathParser.MINUSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MINUS</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMINUS([NotNull] BasicMathParser.MINUSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DIVIDE</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDIVIDE([NotNull] BasicMathParser.DIVIDEContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DIVIDE</c>
	/// labeled alternative in <see cref="BasicMathParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDIVIDE([NotNull] BasicMathParser.DIVIDEContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace BasicMath
